"""Stable pytest nodeids for split test_host_health.py cases."""

# ruff: noqa: F401
from ._host_health_cases_1 import (
    test_checkpoint_progress_defers_zero_traffic_escalation,
    test_collector_batches_reject_blank_node_identity,
    test_continuous_rank_progress_suppresses_within_budget,
    test_efa_inventory_failure_mode_selects_recovery_action,
    test_efa_traffic_spike_and_drop_are_state_transitions,
    test_gpu_low_utilization_email_is_aggregated_per_node,
    test_host_policy_persists_only_metrics_consumed_by_validation,
    test_host_validation_metrics_are_persisted_as_latest,
    test_hung_strace_configuration_rejects_unsafe_bounds,
    test_inventory_card_loss_reboots_then_escalates_to_replacement,
    test_low_utilization_does_not_alert_for_idle_node,
    test_metric_policy_emits_only_active_transition,
    test_missing_rank_liveness_does_not_suppress_escalation,
    test_node_log_does_not_treat_efa_plugin_name_as_rdma_fault,
    test_node_log_uses_highest_severity_matching_rule,
    test_progress_suppression_budget_must_be_positive,
    test_progress_suppression_is_bounded,
    test_rank_liveness_can_be_disabled,
    test_rank_liveness_defers_zero_traffic_escalation,
    test_rdma_link_down_requests_fabric_diagnostics,
    test_rdma_link_error_sends_one_fixed_email,
    test_stalled_ranks_still_escalate_to_hung,
    test_sustained_host_resource_risk_emits_once_and_rearms,
    test_sustained_host_resource_risk_sends_fixed_email,
    test_sustained_host_resource_state_survives_sqlite_restart,
    test_sustained_zero_efa_traffic_captures_hung_context,
    test_zero_traffic_progress_suppression_can_be_disabled,
)
from ._host_health_cases_2 import (
    test_a_tcp_retransmit_raises_no_finding_and_ships_no_batch,
    test_admin_can_accept_new_efa_baseline_and_stale_event_is_rejected,
    test_admin_can_acknowledge_transient_efa_spike,
    test_cpu_finding_requests_host_validation,
    test_efa_inventory_transition_rearms_after_recovery,
    test_efa_rebaseline_is_durable_and_idempotent_in_sqlite,
    test_efa_recovery_workflow_uses_targeted_remediation,
    test_efa_traffic_anomaly_sends_fixed_email,
    test_failed_targeted_efa_recovery_escalates_to_reboot,
    test_genuine_network_error_counters_keep_their_finding,
    test_host_telemetry_endpoint_builds_quarantine_workflow,
    test_inactive_efa_link_diagnoses_then_escalates_to_reboot,
    test_kubernetes_efa_allocatable_loss_restarts_device_plugin,
    test_kubernetes_gpu_allocatable_loss_restarts_device_plugin,
    test_node_log_endpoint_classifies_mce_and_nccl,
)
