"""Render the regional test-case index from its two machine sources.

The spec document is ~18k lines and its case sections are not in execution
order: the phase table in §17 gives the order while the case bodies are
grouped by subsystem. A reader who wants "what runs and in what order"
has nowhere to look.

This builds that view from the files that already have to be right --
``testcases/regional-execution-order.yaml`` for the order and
``testcases/fault-scenarios.yaml`` for the fields -- so it cannot disagree
with them, and ``--check`` makes a stale index a test failure instead of a
silently wrong table.

Deliberately not written by hand and deliberately not a third source of
truth: nothing here is authored, every column is read off one of the two
YAMLs or the catalog's own ``procedure`` anchor.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import yaml


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

from tools.run_fault_test_cases import load_catalog  # noqa: E402

ORDER = ROOT / "testcases" / "regional-execution-order.yaml"
CATALOG = ROOT / "testcases" / "fault-scenarios.yaml"
OUTPUT = ROOT / "docs" / "区域用例索引.md"
DOCUMENT = "区域模式端到端验收测试用例.md"


def ordered_cases(order: dict) -> list[tuple[dict, list[str]]]:
    phases = sorted(order["phases"], key=lambda item: item["sequence"])
    result = []
    for phase in phases:
        cases: list[str] = []
        for entry in phase["entries"]:
            if "case" in entry:
                cases.append(entry["case"])
                continue
            item = entry["range"]
            cases.extend(
                f"GF-REGIONAL-{item['prefix']}-{number:03d}"
                for number in range(item["start"], item["end"] + 1)
            )
        result.append((phase, cases))
    return result


def automation_of(case: dict) -> str:
    label = case["automation"]
    if "related_pytest" in case:
        return f"{label} + 单测"
    return label


def body_link(case: dict) -> str:
    procedure = case.get("procedure")
    if isinstance(procedure, str) and "#" in procedure:
        path, _, anchor = procedure.partition("#")
        return f"[§]({Path(path).name}#{anchor})"
    nodeid = case.get("pytest_nodeid")
    if isinstance(nodeid, str):
        return f"`{nodeid.split('::', 1)[1]}`"
    return "—"


def render() -> str:
    order = yaml.safe_load(ORDER.read_text(encoding="utf-8"))
    catalog = {
        case["id"]: case
        for case in load_catalog(CATALOG)
        if case["id"].startswith("GF-REGIONAL-")
    }
    phases = ordered_cases(order)
    do_not_run = order.get("do_not_run") or []
    total = sum(len(cases) for _, cases in phases) + len(do_not_run)
    missing = sorted(
        case_id for _, cases in phases for case_id in cases if case_id not in catalog
    )
    if missing:
        raise SystemExit(f"execution order references uncatalogued cases: {missing}")

    lines = [
        "# 区域分离部署用例索引（按执行顺序）",
        "",
        "<!-- Generated by scripts/build-regional-case-index.py; do not edit. -->",
        "",
        "本文件是**生成物**，不要手改。它回答两个问题：**跑什么、",
        "按什么顺序跑**。事实源只有两个：",
        "",
        f"- 顺序：`{ORDER.relative_to(ROOT)}`（`sequence` 升序，"
        "phase 内按 `entries` 展开）",
        f"- 字段：`{CATALOG.relative_to(ROOT)}`",
        "",
        f"用例正文见 [`{DOCUMENT}`]({DOCUMENT})；"
        "「正文」列直接跳到该用例的小节。"
        "真实环境的执行结论和现场标识保存在不公开的内部证据库中，"
        "不进入本索引。",
        "重新生成：`python3 scripts/build-regional-case-index.py`。",
        "",
        f"共 **{total}** 条：{total - len(do_not_run)} 条按阶段执行，"
        f"{len(do_not_run)} 条 `DO_NOT_RUN`。",
        "",
        "## 阶段总览",
        "",
        "| 阶段 | 名称 | 条数 | 维护窗口 | 前置 |",
        "| --- | --- | --- | --- | --- |",
    ]
    for phase, cases in phases:
        window = phase["maintenance_window"]
        if window == "是":
            window = "**是**"
        prerequisite = phase.get("prerequisite") or "—"
        lines.append(
            f"| {phase['sequence']} | {phase['name']} | "
            f"{len(cases)} | {window} | {prerequisite} |"
        )
    lines.append("")

    position = 0
    for phase, cases in phases:
        lines.append(f"## 阶段 {phase['sequence']} — {phase['name']}")
        lines.append("")
        window = phase["maintenance_window"]
        if window == "是":
            lines.append("> **需要维护窗口。**")
            lines.append("")
        elif window == "分级":
            lines.append(
                "> **维护窗口按用例分级**：本阶段用例副作用不同，逐条看「等级」列。"
            )
            lines.append("")
        elif window == "建议":
            lines.append("> 建议在维护窗口执行。")
            lines.append("")
        if phase.get("prerequisite"):
            lines.append(f"> 前置：{phase['prerequisite']}")
            lines.append("")
        for note in phase.get("notes") or []:
            lines.append(f"> - {note}")
        if phase.get("notes"):
            lines.append("")
        lines.append("| # | 用例 | 标题 | 等级 | 层级 | 自动化 | 正文 |")
        lines.append("| --- | --- | --- | --- | --- | --- | --- |")
        for case_id in cases:
            case = catalog[case_id]
            position += 1
            lines.append(
                f"| {position} | `{case_id.removeprefix('GF-REGIONAL-')}` | "
                f"{case['title']} | `{case['risk']}` | "
                f"{case['level']} | {automation_of(case)} | "
                f"{body_link(case)} |"
            )
        lines.append("")

    if do_not_run:
        lines.append("## DO_NOT_RUN（只保留历史编号）")
        lines.append("")
        lines.append("| 用例 | 标题 | 作废理由 | 正文 |")
        lines.append("| --- | --- | --- | --- |")
        for entry in do_not_run:
            case = catalog[entry["case"]]
            lines.append(
                f"| `{entry['case'].removeprefix('GF-REGIONAL-')}` | "
                f"{case['title']} | {entry.get('reason', '—')} | "
                f"{body_link(case)} |"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(
                "regional case index is stale; run "
                "python3 scripts/build-regional-case-index.py",
                file=sys.stderr,
            )
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
