from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "gpu_fault"
OUTPUT = ROOT / "docs" / "环境变量参考.md"
INVENTORY_OUTPUT = ROOT / "src" / "gpu_fault" / "data" / "env-inventory.json"
DEPLOY_ENV_SOURCES = (
    ROOT / "deploy" / "node" / "install-gpu-fault-collector.sh",
    ROOT / "deploy" / "node" / "verify-gpu-fault-collector.sh",
    *(ROOT / "deploy" / "systemd").glob("*"),
)
NAME_PATTERN = re.compile(r"\bGPU_FAULT_[A-Z0-9_]+\b")
DYNAMIC_PREFIXES = ("GPU_FAULT_NOTIFICATION_TTL_SECONDS_",)
DYNAMIC_VARIABLES = tuple(
    f"GPU_FAULT_PROCESSOR_{prefix}ADMISSION_{suffix}"
    for prefix in ("", "FAULT_", "EVIDENCE_")
    for suffix in (
        "BATCH_SIZE",
        "BATCH_GROUPS",
        "BATCH_DELAY_SECONDS",
        "PROJECTION_MARGIN",
    )
)


def module_name(path: Path) -> str:
    relative = path.relative_to(SOURCE).with_suffix("")
    parts = list(relative.parts)
    if parts[-1] == "__init__":
        parts.pop()
    return "gpu_fault." + ".".join(parts)


def deployment_source_name(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def expression(node: ast.AST | None) -> str:
    if node is None:
        return ""
    try:
        return ast.unparse(node).replace("\n", " ")
    except Exception:
        return ""


def extract() -> tuple[dict[str, set[str]], dict[str, set[str]]]:
    modules: dict[str, set[str]] = defaultdict(set)
    defaults: dict[str, set[str]] = defaultdict(set)
    for path in sorted(SOURCE.rglob("*.py")):
        text = path.read_text(encoding="utf-8")
        tree = ast.parse(text)
        module = module_name(path)
        for node in ast.walk(tree):
            if isinstance(node, ast.Constant) and isinstance(node.value, str):
                for name in NAME_PATTERN.findall(node.value):
                    modules[name].add(module)
            if not isinstance(node, ast.Call) or not node.args:
                continue
            first = node.args[0]
            if not (
                isinstance(first, ast.Constant)
                and isinstance(first.value, str)
                and NAME_PATTERN.fullmatch(first.value)
            ):
                continue
            name = first.value
            modules[name].add(module)
            if len(node.args) > 1:
                defaults[name].add(expression(node.args[1]))
        for node in ast.walk(tree):
            if not isinstance(node, ast.Subscript):
                continue
            value = node.value
            if not (
                isinstance(value, ast.Attribute)
                and isinstance(value.value, ast.Name)
                and value.value.id == "os"
                and value.attr == "environ"
            ):
                continue
            key = node.slice
            if (
                isinstance(key, ast.Constant)
                and isinstance(key.value, str)
                and NAME_PATTERN.fullmatch(key.value)
            ):
                modules[key.value].add(module)
                defaults[key.value].add("<required>")
    for name in DYNAMIC_VARIABLES:
        modules[name].add("gpu_fault.app.admission_runtime")
        defaults[name].add("<dynamic>")
    for path in sorted(DEPLOY_ENV_SOURCES):
        if not path.is_file():
            continue
        source = deployment_source_name(path)
        for name in NAME_PATTERN.findall(path.read_text(encoding="utf-8")):
            modules[name].add(source)
    return modules, defaults


def domain(name: str) -> str:
    groups = (
        (
            "PostgreSQL",
            ("GPU_FAULT_POSTGRES_", "GPU_FAULT_STORE_"),
        ),
        ("Processor", ("GPU_FAULT_PROCESSOR_",)),
        (
            "Agent/Fleet",
            ("GPU_FAULT_AGENT_", "GPU_FAULT_NODE_"),
        ),
        (
            "Notification",
            ("GPU_FAULT_NOTIFICATION_", "GPU_FAULT_SES_"),
        ),
        (
            "Telemetry",
            (
                "GPU_FAULT_GPU_",
                "GPU_FAULT_HOST_",
                "GPU_FAULT_EFA_",
                "GPU_FAULT_DCGM_",
                "GPU_FAULT_TELEMETRY_",
            ),
        ),
        ("HyperPod", ("GPU_FAULT_HYPERPOD_",)),
        ("Workflow", ("GPU_FAULT_WORKFLOW_",)),
    )
    for label, prefixes in groups:
        if name.startswith(prefixes):
            return label
    return "Core/Other"


def render() -> str:
    modules, defaults = extract()
    lines = [
        "# 环境变量参考",
        "",
        "<!-- Generated by scripts/generate-env-reference.py; do not edit. -->",
        "",
        f"当前代码自动识别到 **{len(modules)}** 个 `GPU_FAULT_*` 配置项。",
        "修改代码中的配置项后必须重新生成本表。",
        "",
        "| 环境变量 | 领域 | 默认值/要求 | 使用模块 |",
        "|---|---|---|---|",
    ]
    for name in sorted(modules):
        default = ", ".join(sorted(defaults.get(name, {"<implicit>"})))
        used = "<br>".join(f"`{item}`" for item in sorted(modules[name]))
        lines.append(f"| `{name}` | {domain(name)} | `{default}` | {used} |")
    return "\n".join(lines) + "\n"


def render_inventory() -> str:
    modules, _ = extract()
    return (
        json.dumps(
            {
                "schema_version": 1,
                "variables": sorted(modules),
                "dynamic_prefixes": list(DYNAMIC_PREFIXES),
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    expected_inventory = render_inventory()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        actual_inventory = (
            INVENTORY_OUTPUT.read_text(encoding="utf-8")
            if INVENTORY_OUTPUT.exists()
            else ""
        )
        if actual != expected or actual_inventory != expected_inventory:
            print(
                "environment reference/inventory is stale; run "
                "python3 scripts/generate-env-reference.py",
                file=sys.stderr,
            )
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    INVENTORY_OUTPUT.write_text(
        expected_inventory,
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
