from gpu_fault.notifications.common import (
    SXID_EVENT_EMAIL_TEMPLATE,
    SXID_EVENT_TEMPLATE_VERSION,
    AdvisoryNotification,
)


class SxidEventEmailBuilder:
    """Renders the fixed notification emitted for every SXID event."""

    def build(
        self,
        *,
        cluster_id: str,
        node_id: str,
        incident_id: str,
        workflow_id: str | None,
        event_id: str,
        sxid: int,
        product: str | None,
        observed_at: str,
        event_source: str | None,
        evidence_ref: str | None,
        workload_state: str,
        workload_ids: list[str],
        classification: str,
        classification_source: str,
        link_scope: str,
        link_scope_source: str | None,
        switch_id: str | None,
        port: str | None,
        pci_bdf: str | None,
        fabric_partition: str | None,
        disposition: str,
        official_action: str | None,
        effective_action: str | None,
        safety_action: str | None,
        investigatory_action: str | None,
        policy_source: str,
        policy_version: str,
        reasons: list[str],
    ) -> AdvisoryNotification:
        body = SXID_EVENT_EMAIL_TEMPLATE.format(
            cluster_id=cluster_id,
            node_id=node_id,
            sxid=sxid,
            product=product or "UNKNOWN",
            observed_at=observed_at,
            event_id=event_id,
            event_source=event_source or "UNKNOWN",
            evidence_ref=evidence_ref or "NONE",
            workload_state=workload_state,
            workloads=", ".join(workload_ids) or "NONE",
            classification=classification,
            classification_source=classification_source,
            link_scope=link_scope,
            link_scope_source=link_scope_source or "UNKNOWN",
            switch_id=switch_id or "UNKNOWN",
            port=port or "UNKNOWN",
            pci_bdf=pci_bdf or "UNKNOWN",
            fabric_partition=fabric_partition or "UNKNOWN",
            disposition=disposition,
            official_action=official_action or "NONE",
            effective_action=effective_action or "NONE",
            safety_action=safety_action or "NONE",
            investigatory_action=investigatory_action or "NONE",
            policy_source=policy_source,
            policy_version=policy_version,
            reasons=("\n".join(f"  - {item}" for item in reasons) or "  - NONE"),
            incident_id=incident_id,
            workflow_id=workflow_id or "NONE",
            template_version=SXID_EVENT_TEMPLATE_VERSION,
        )
        return AdvisoryNotification(
            deduplication_key=(f"{event_id}/sxid-event/{SXID_EVENT_TEMPLATE_VERSION}"),
            cluster_name=cluster_id,
            incident_id=incident_id,
            subject=(f"[GPU故障][SXID {sxid}] {cluster_id} {node_id}"),
            body_text=body,
            support_case_draft="",
            evidence_refs=([evidence_ref] if evidence_ref else []),
        )
