"""Stable pytest nodeids for split test_postgres_processor_claim.py cases."""

# ruff: noqa: F401
from ._postgres_processor_claim_cases_1 import (
    pytestmark,
    test_claim_keeps_one_request_per_lane,
    test_claim_prefers_faults_over_telemetry_across_the_window,
    test_claim_window_returns_oldest_and_bounds_the_scan,
    test_completed_request_is_not_reclaimed,
    test_expired_lease_is_reclaimed,
    test_fault_waits_for_the_correlated_observation,
    test_lane_cleanup_skips_lanes_that_still_hold_work,
    test_partitioned_counters_separate_fault_and_low_priority,
    test_partitioned_evidence_admission_ignores_fault_shard_lock,
    test_partitioned_evidence_and_routine_shards_do_not_block,
    test_partitioned_fault_admission_ignores_locked_evidence_shard,
    test_path_filters_still_scope_the_window,
    test_postgres_enqueue_notifies_waiting_consumers,
    test_postgres_notification_shard_has_one_owner,
    test_postgres_reports_priority_zero_backlog,
    test_postgres_routine_aging_prevents_starvation,
    test_postgres_spool_abandon_preserves_retry_budget,
    test_postgres_spool_admission_notifies_dedicated_channel,
    test_postgres_spool_claim_respects_payload_byte_budget,
    test_postgres_spool_claim_uses_the_path_index,
    test_postgres_spool_claims_and_completes_sixty_four_rows,
    test_queue_counters_track_bulk_statements,
)
from ._postgres_processor_claim_cases_2 import (
    test_admission_group_is_one_insert_statement,
    test_admission_group_rejects_duplicate_request_ids,
    test_cluster_cap_stays_exact_at_the_boundary,
    test_completion_batch_is_one_statement_per_cluster,
    test_completion_batch_still_fences_each_request,
    test_completion_holds_one_cluster_counter_row_at_a_time,
    test_concurrent_admissions_to_one_cluster_do_not_serialize,
    test_concurrent_fault_admissions_do_not_serialize,
    test_counter_shard_finalize_requires_an_empty_queue,
    test_expired_remote_lease_is_reclaimed,
    test_fault_path_cluster_cap_stays_exact_at_the_boundary,
    test_leased_command_cancellation_is_requested_not_forced,
    test_multi_cluster_batches_do_not_deadlock_on_the_counters,
    test_partitioned_priority_shards_have_a_total_lock_order,
    test_release_leaves_a_completed_request_completed,
    test_remote_claim_honours_advertised_owners,
    test_remote_claim_skips_stale_fencing_and_other_clusters,
    test_remote_commands_are_leased_in_one_batch,
    test_single_cluster_completion_batch_stays_one_statement,
    test_workflow_cancellation_only_touches_its_own_commands,
)
from ._postgres_processor_claim_support import store
